### ISSUE TITLE
Packagist update to v2.1.2

### ISSUE THREAD

**Issue by cuhsat** [asgoodasnu/SofortLib-PHP-Payment#3]
Not really a issue, but could you please create the new version `v2.1.2` at the packagist.org? I would like to nail down version 2.1.2 in my composer file and rather not rely on `dev-master`. 

https://packagist.org/packages/asgoodasnu/sofortlib-php-payment

**Comment by simonchrz** [comment]
done :-)

**Comment by cuhsat** [comment]
Thank you! :)
